# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-08 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupid',
            field=models.CharField(blank=True, default='[689685]', editable=False, max_length=6, unique=True),
        ),
    ]
