# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-07 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='member_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
