# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-07 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_member_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='member_count',
        ),
    ]
