# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-08 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_auto_20200608_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='groupid',
        ),
    ]
