# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-08 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_remove_group_groupid'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='groupid',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
    ]
