# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-16 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_auto_20200611_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='groupid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
