# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-16 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0016_group_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupid',
            field=models.CharField(max_length=10),
        ),
    ]
