# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-08 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['pk']},
        ),
    ]
