# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-16 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200611_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='memberid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
