# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-07-05 02:58
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
