# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-09 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.PositiveIntegerField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('LIFE', 'Life Insurance'), ('STD', 'Short Term Disability'), ('LTD', 'Long Term Disability'), ('CI', 'Critical Illness')], default='LIFE', max_length=100)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('description', models.TextField(blank=True, default='')),
                ('description_html', models.TextField(blank=True, default='', editable=False)),
                ('coverage_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_1000_dollars', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('name', 'type')]),
        ),
    ]
