# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-10 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200609_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Unknown Type', 'Unknown Type'), ('LIFE', 'Life Insurance'), ('STD', 'Short Term Disability'), ('LTD', 'Long Term Disability'), ('CI', 'Critical Illness')], default='Unknown Type', max_length=100),
        ),
    ]
