# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-13 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200611_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coverage_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
