# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-11 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_auto_20200611_0243'),
        ('groups', '0012_auto_20200608_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('description', models.TextField(blank=True, default='')),
                ('description_html', models.TextField(blank=True, default='', editable=False)),
                ('coverage_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('agreement_date', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_set', to='groups.Group')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_set', to='products.Product')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
