# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-11 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='agreement_date',
            field=models.DateTimeField(),
        ),
    ]
