# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-12 03:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200611_2203'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agreements', '0006_agreement_agreement_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'ordering': ['-agreement_date']},
        ),
        migrations.AddField(
            model_name='agreement',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='product',
        ),
        migrations.AddField(
            model_name='agreement',
            name='product',
            field=models.ManyToManyField(related_name='product_set', to='products.Product'),
        ),
    ]
