# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-13 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0007_auto_20200612_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_set', to='groups.Group'),
        ),
    ]
