# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-14 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0008_auto_20200613_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='coverage_limit',
        ),
    ]
