# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-16 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0010_auto_20200615_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='agreementid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
