# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-18 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0011_agreement_agreementid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='product',
        ),
        migrations.AddField(
            model_name='agreement',
            name='product',
            field=models.CharField(choices=[('Unknown Type', 'Unknown Type'), ('LIFE', 'Life Insurance'), ('STD', 'Short Term Disability'), ('LTD', 'Long Term Disability'), ('CI', 'Critical Illness')], default='Unknown Type', max_length=100),
        ),
    ]
