# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-18 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0012_auto_20200618_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements_products_set', to='groups.Group'),
        ),
    ]
