# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-07-05 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0014_auto_20200619_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='coverage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='agreement',
            name='price_per_1000_units',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
